[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    X-Made-By = "@dalagan"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    Referrer-Policy = "no-referrer-when-downgrade"

# Redirect everything from /s/ for direct linking
# https://www.netlify.com/docs/redirects/#structured-configuration
[[redirects]]
  from   = "/s/*"
  to     = "/index.html"
  status = 200
  force  = true
