# Redirect everything from /s/ for direct linking
# https://www.netlify.com/docs/redirects/#structured-configuration
[[redirects]]
  from   = "/s/*"
  to     = "/index.html"
  status = 200
  force  = true

[[headers]]
  for = "/*"
  [headers.values]
    # https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy
    Referrer-Policy = "same-origin"

    # https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options
    # I never intend to show any of the pages on my site in a <frame> on my site
    # or elsewhere.
    X-Frame-Options = "DENY"

    # https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-XSS-Protection
    X-Xss-Protection = "1; mode=block"

    # https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Content-Type-Options
    X-Content-Type-Options = "nosniff"

    X-Made-By = "@dalagan"
    
    # https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security
    # https://hstspreload.org/
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"

    ### Content Security Policy (CSP)
    # https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy
    # default-src: Define loading policy for all resources type in case of a
    # resource type dedicated directive is not defined (fallback). For better
    # safety, set this to 'none'.

    # frame-ancestors: Specifies valid parents that may embed a page using
    # <frame>, <iframe>, <object>, <embed>, or <applet>. I don't use frames, so
    # set this to 'none'.

    # base-uri: When set to 'none' or 'self', restricts the use of <base>
    # tag. https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/base-uri

    # block-all-mixed-content: Prevents loading any assets using HTTP when the
    # page is loaded using HTTPS.

    # report-uri: URI to send the CSP reports to, https://report-uri.com/

    # When debugging CSP rules, set the header to
    # Content-Security-Policy-Report-Only instead of Content-Security-Policy.
    # - https://scotthelme.co.uk/content-security-policy-an-introduction/#testingapolicy
    # Content-Security-Policy-Report-Only = """
    # Content-Security-Policy = """
       # default-src 'none'; 
        #style-src 'self' https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/ https://fonts.googleapis.com/ https://use.fontawesome.com/releases/v5.8.1/css/
        #font-src https://fonts.gstatic.com https://use.fontawesome.com; 
        #base-uri 'self';
        #"""
    # frame-ancestors 'none';    
    # block-all-mixed-content;
    # form-action 'self';
    # object-src 'none';
    # img-src 'self'; 
    # style-src 'self' 'unsafe-inline';

    # Feature Policy
    # https://developers.google.com/web/updates/2018/06/feature-policy

    # |----------------------+-------------------+--------------------------------------------------------------|
    # | Feature name         | Default allowlist | Brief Description                                            |
    # |----------------------+-------------------+--------------------------------------------------------------|
    # | accelerometer        | self              | Controls access to accelerometer sensors on the device       |
    # | ambient-light-sensor | self              | Controls access to ambient light sensors on the device       |
    # | autoplay             | self              | Controls access to autoplay through `play()` and `autoplay`. |
    # | camera               | self              | Controls access to video input devices.                      |
    # | encrypted-media      | self              | Controls whether `requestMediaKeySystemAccess()` is allowed. |
    # | fullscreen           | self              | Controls whether `requestFullscreen()` is allowed.           |
    # | geolocation          | self              | Controls access to Geolocation interface.                    |
    # | gyroscope            | self              | Controls access to gyroscope sensors on the device           |
    # | magnetometer         | self              | Controls access to magnetometer sensors on the device        |
    # | microphone           | self              | Controls access to audio input devices.                      |
    # | midi                 | self              | Controls access to `requestMIDIAccess()` method.             |
    # | payment              | self              | Controls access to PaymentRequest interface.                 |
    # | picture-in-picture   | *                 | Controls access to Picture in Picture.                       |
    # | speaker              | self              | Controls access to audio output devices.                     |
    # | usb                  | self              | Controls access to USB devices.                              |
    # | vr                   | self              | Controls access to VR displays.                              |
    # |----------------------+-------------------+--------------------------------------------------------------|
    Feature-Policy = """
        accelerometer 'none';
        ambient-light-sensor 'none';
        autoplay 'self';
        camera 'none';
        encrypted-media 'none';
        fullscreen 'self';
        geolocation 'none';
        gyroscope 'none';
        magnetometer 'none';
        microphone 'none';
        midi 'none';
        payment 'none';
        picture-in-picture *;
        speaker 'none';
        sync-xhr 'none';
        usb 'none';
        vr 'none'
    """   
    
    # Multi-key header rules are expressed with multi-line strings
    Link = '''
    </assets/css/base.css>; rel=preload; as=style, \
    </assets/css/base2.css>; rel=preload; as=style, \
    </assets/css/base3.css>; rel=preload; as=style'''
