[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    X-Made-By = "@dalagan"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    Referrer-Policy = "same-origin"
    #Content-Security-Policy = """
        #style-src 'self' 'unsafe-inline';
        #frame-ancestors 'none';
        #object-src 'none';
        #base-uri 'none';
        #upgrade-insecure-requests;
        #block-all-mixed-content;
    
    # Multi-key header rules are expressed with multi-line strings
    Link = '''
    </assets/css/base.css>; rel=preload; as=style, \
    </assets/css/base2.css>; rel=preload; as=style, \
    </assets/css/base3.css>; rel=preload; as=style'''
    
# Redirect everything from /s/ for direct linking
# https://www.netlify.com/docs/redirects/#structured-configuration
[[redirects]]
  from   = "/s/*"
  to     = "/index.html"
  status = 200
  force  = true
