[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = 1; mode=block
    X-Content-Type-Options = "nosniff"
    X-Made-By = "@dalagan"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    Referrer-Policy = "no-referrer-when-downgrade"
    # CSP Policy
    # Report only
    # Note: Report only policy doesn't have 'upgrade-insecure-requests' as this does nothing in report-only
    ##Content-Security-Policy-Report-Only = '''
    ##default-src 'none' ; 
    ##img-src 'self' data: ; 
    ##font-src 'none' ; 
    ##form-action 'self' ; 
    ##block-all-mixed-content; 
    # Live rules -  be careful!
    Content-Security-Policy = '''
    default-src 'none' ; 
    font-src 'none' ;
    form-action 'self' ;
    upgrade-insecure-requests;
    block-all-mixed-content;

[[headers]]
  for = "/"
  [headers.values]
    # Preload links
    Link = '''
    </css/main.css?v=1.0.0>; rel=preload; as=style, 
    </js/app.js?v=1.0.0>; rel=preload; as=script, 
    </js/validate-ip.js?v=1.0.0>; rel=preload; as=script'''

[[headers]]
  for = "/s/*"
  [headers.values]
    # Preload links
    Link = '''
    </css/main.css?v=1.0.0>; rel=preload; as=style, 
    </js/app.js?v=1.0.0>; rel=preload; as=script, 
    </js/validate-ip.js?v=1.0.0>; rel=preload; as=script'''

# Redirect everything from /s/ for direct linking
# https://www.netlify.com/docs/redirects/#structured-configuration
[[redirects]]
  from   = "/s/*"
  to     = "/index.html"
  status = 200
  force  = true
